### ISSUE TITLE
Encrypting fields of superclasses

### ISSUE THREAD

**Issue by ngbalk** [bolcom/spring-data-mongodb-encrypt#12]
https://github.com/bolcom/spring-data-mongodb-encrypt/blob/cdc2f9b450355cf6edfa0a8d1c1d8d8daf1fe5fd/src/main/java/com/bol/reflection/ReflectionCache.java#L20

How would this work if we have an object Person that extends some object Entity that has a field that needs to be @Encrypted.  Or a slightly different case, where Person has a field Ssn that extends Identifier that has a field that needs to be @Encrypted.  Would this handle that / do you think it would be difficult to support such a feature?  I hope I explained that well but let me know if you need more details about the issue I am bringing up.

**Comment by agoston** [comment]
Interesting question, I think it should work, but will add a system test coverage for this case.
You can just try it and check if it's encrypted in mongo?

**Comment by agoston** [comment]
You were right, inherited fields were indeed not working.
Fixed in 1.3.0-SNAPSHOT. I will make a final release soon.
