### ISSUE TITLE
Not support DBRef

### ISSUE THREAD

**Issue by pltchuong** [bolcom/spring-data-mongodb-encrypt#16]
If my nested bean has annotation `@DBRef`, the encryption would fail and throw me an exception `Unknown class field to crypt for field xxx: class com.mongodb.DBRef`

**Comment by agoston** [comment]
Correct, DBRef's are not supported by this version.

Keep in mind if you would encrypt DBRef's, you would lose all the reasons you opted for DBRef's in the first place (easy lookup).

If you can make a working patch, I'd be happy to merge a pull request!

**Comment by pltchuong** [comment]
But, what if I don't need to encrypt DBRef? I just simply want to ignore DBRef at this moment.

**Comment by agoston** [comment]
DBRef points to a document in a different collection. You could try using @Encrypted on the fields of the sub-document. YMMV, I've never tried that, but in theory, it could work.

Remember DBRef is stored as a normal field in mongo, it's the java driver that does you some extra round-trips to the mongo server to fetch the document it points to.

**Comment by pltchuong** [comment]
That works, that's what i'm using now. But my question is, I wanted to save main document, but it has a property with `@DBRef`, and of course point to a sub-document. All I wanted to do is save this main document but I cannot, is there anyway around?

**Comment by agoston** [comment]
Can you copy the @Document objects here, and the code snippet that fails? It would be easier to help your specific situation.
