### ISSUE TITLE
Index on encrypted fields possible?

### ISSUE THREAD

**Issue by CloudResearch** [bolcom/spring-data-mongodb-encrypt#20]
Is it possible to use encryption on indexed fields, like an email? Is there a draw back, slow speed?

**Comment by agoston** [comment]
This lib encrypts data _before_ it is sent to mongodb. As such, you can add index on encrypted fields, but it doesn't make any sense, as mongodb will see garbage only, and you won't be able to do search on these (that's the idea of encryption, eh :D )

What you can do: store the non-indexed encrypted field normally, and store an indexed hash of the email. When you need to search by the email, hash it again and search on that in the db; if you'd encounter multiple hits, read those from mongo and match the decrypted email to find the document you were looking for.

**Comment by CloudResearch** [comment]
Thank you for the tip with hashing, works like a charm!

**Comment by agoston** [comment]
Thanks, I've added a section in the doc to cover this question.
