### ISSUE TITLE
Cannot encrypt a field which is an interface

### ISSUE THREAD

**Issue by pzn** [bolcom/spring-data-mongodb-encrypt#22]
Hey @agoston,

Very nice work with this library!

I found an interesting situation where the library is not able to encrypt fields which are implementing an interface, interface which is referenced by a parent bean.

Something like:
```
class MyBean {
	@Id
	String id;
	Stuff stuff;
}

interface MyStuff {

}

class Key implements MyStuff {
	@Encrypted
	String lock;
	@Encrypted
	int weight;

	public static Key someKey(int weight, String lock) {
		Key key = new Key();
		key.weight = weight;
		key.lock = lock;
		return key;
	}
}

interface MyBeanRepository extends MongoRepository<MyBean, String> {

}
```

Encryption doesn't happen on Key's `lock` and `weight`:
![image](https://user-images.githubusercontent.com/553311/61174540-94540d00-a56f-11e9-99a6-8fa9af64c7c5.png)

I tested using `CachedEncryptionEventListener`.

Here's a code sample: https://github.com/pzn/spring-data-mongodb-encrypt-demo

**Comment by pzn** [comment]
After debugging the lib, it seems to be related to https://github.com/bolcom/spring-data-mongodb-encrypt/blob/a9d5ee0dfc5d84dda0dac99a8922982de739b647/src/main/java/com/bol/reflection/ReflectionCache.java#L30, which is retrieving class' fields.

When analyzing `MyBean`, it checks `MyStuff` which is an interface and... doesn't have any fields! So nothing won't be cached.

Then later dring `onAfterLoad`/`onBeforeSave` when reaching the list of `MyStuff`, since nothing has been cached, everything will be skipped!

**Comment by agoston** [comment]
Yes, but you are trying to use polymorphism with the CachedEncryptionEventListener. Please read the relevant part of the documentation and switch to ReflectionEncryptionEventListener (or, better yet, don't use polymorphism in your data model - it will do more damage than good in the long run).
