### ISSUE TITLE
Add auto-configuration based on sane defaults

### ISSUE THREAD

**Issue by agoston** [bolcom/spring-data-mongodb-encrypt#23]
At the moment it's quite a hurdle to set up spring context for encryption. Add sane defaults and property-based auto-configuration for that 99% of use cases.

**Comment by hammingweight** [comment]
For what it's worth, I have some crude autoconfiguration code to simplify my working with the library https://github.com/hammingweight/spring-data-mongodb-encrypt-autoconfiguration It may be too primitive for other use cases.

**Comment by agoston** [comment]
Love it! Mind it I shamelessly steal it, almost as it is? Or, you can do a merge request!

**Comment by hammingweight** [comment]
Either is OK with me :).

I'm happy to create a pull request but the configuration property needs a name without "hammingweight" in it. Shall I replace hammingweight with "bolcom" or something similar?

**Comment by agoston** [comment]
This has been added in 2.4.0.

In the end I did use your code for inspiration, but my approach is quite different.

Thanks for the contribution!
