### ISSUE TITLE
Find opertions don't work as expected using CrudRepository

### ISSUE THREAD

**Issue by hannojg** [bolcom/spring-data-mongodb-encrypt#29]
Hello, 

I have certain fields that I want to encrypt in a document. I pulled in this library, set everything up and encrypted the specific fields. 
However, my data tests that are using `findByFIELDNAME` from CurdRepository are failing. 

I will set up a demo so that you can see and reproduce the issue. Maybe I am missing something and finding is not possible when using encrypted fields and I would have to use hashes next to the field. Any guidance would be appreciated! Thank you so much in advance!

**Comment by agoston** [comment]
If you manage to gather more info, I'd be more than happy to hear about it!

Just FYI, of course you can't use any of the @Encrypted fields in any of the crudrepository methods. Its contents are mangled from mongodb. Check the doc for ideas how to circumvent that.
