### ISSUE TITLE
perform a search of an encrypted field

### ISSUE THREAD

**Issue by cardinal76** [bolcom/spring-data-mongodb-encrypt#34]
Hi, is it possible to perform a search of an encrypted field or to implement it?
For example, I have to search a field that before encrypting was a string and now a binary field
I need to perform a like too, to that field.

**Comment by agoston** [comment]
Please read the relevant part of the documentation .

**Comment by cardinal76** [comment]
Thanks Agoston
Could you indicate me which is the relevant part? Please.
Could I contact you in anyway?

**Comment by agoston** [comment]
You have to decide what you want. You want data not to be a secret, hence you encrypt it. But then you want your data to be available for full-text index and search. These are contradicting requirements. From a full-text index, you can more or less reconstruct the data itself.

You can't use the 'encrypt other data' method here. Encryption makes sure every time you encrypt, the crypted form is completely different. That's the whole point of encryption.

The recommendation is to create a hash of the data (in this case, a string), and store that alongside its encrypted form. Then query for the hash of the string upon lookup.

**Comment by cardinal76** [comment]
ok, thanks for your answers.
