### ISSUE TITLE
Confusing class name: EncryptAutoConfiguration

### ISSUE THREAD

**Issue by elijah-pl** [bolcom/spring-data-mongodb-encrypt#35]
By convention, `*AutoConfiguration` prefix should be only applied to config classes that are picked up automatically by `spring-boot-autoconfigure` module.

So I can see two options here:
1. Rename the class and explicitly add `@Import(NewClassName.class)` to README instructions in order to make it clear that **it's not an auto-configuration**.
2. Add `spring.factories` file with auto-configuration definition, so config is applied automatically.

**Comment by agoston** [comment]
Thanks for letting me know. Just released 2.4.4 to address this (added spring.factories).
