### ISSUE TITLE
ExistsBy<EncryptedField> doesn't work 

### ISSUE THREAD

**Issue by solveretur** [bolcom/spring-data-mongodb-encrypt#36]
In my application I have a mongo document entity with encrypted field `username` by your library.
```
@Document(value = "Account")
internal data class AccountDocument(
    @Id
    val id: String,
    val appUserId: String,
    @Field
    @Encrypted
    val username: String,
    @Field
    @Encrypted
    val password: String,
    val lastUpdateTimestamp: LocalDateTime,
    val insertTimestamp: LocalDateTime,
    val isDisabled: Boolean = false
)
```
I want to be able to check whether an account with a certain username already exists in my database so I created a `ReactiveMongoRepository`:
```
@Repository
internal interface MongoAccountDocumentRepository : ReactiveMongoRepository<AccountDocument, String> {
    fun existsByUsername(username: String): Mono<Boolean>
}
```
Sadly when I tested my solution I noticed it doesn't work and it always returns false. How to make it work ? Is it so that I can't search by encrypted fields out of a box and I need to do it manually ?

**Comment by elijah-pl** [comment]
@solveretur Well, it makes sense to me.

Your **raw** username value is used to build the query, then that query is executed directly on database and Mongo returns an empty result set. So, basically, there is nothing to decrypt on Kotlin side.

**Comment by agoston** [comment]
Please read https://github.com/bolcom/spring-data-mongodb-encrypt/issues/34
