### ISSUE TITLE
Example of overrride of mappingMongoConverter() to disable reflection is outdated

### ISSUE THREAD

**Issue by gerry-christiansen** [bolcom/spring-data-mongodb-encrypt#43]
Do you have an exapmle that works with the updated Spring AbstractMongoClientConfiguration as AbstractMongoConfiguration is no longer in newer versions of spring boot and the super class signature has changed.

**Comment by agoston** [comment]
I will peek into this.

**Comment by agoston** [comment]
Thanks for reporting this!

I've updated the library dependencies, along with it upgraded to spring-data 3 and mongo-java-driver 4.

I'll archive the spring-data 2 into a branch now, just like I did with spring-data 1, and update the documentation.

For reference, this is how you can make this happen under spring-data 3:
https://github.com/bolcom/spring-data-mongodb-encrypt/blob/master/src/test/java/com/bol/system/cached/CachedMongoDBConfiguration.java

**Comment by gerry-christiansen** [comment]
Your welcome!  Love the library, works awesome!
