### ISSUE TITLE
Deterministic Encryption and Random Encryption (CSFLE MongoDB)

### ISSUE THREAD

**Issue by serafimpinto** [bolcom/spring-data-mongodb-encrypt#46]
It will be possible to support Deterministic Encryption and Random Encryption? 

https://docs.mongodb.com/manual/core/security-client-side-encryption/#deterministic-encryption

```
String DETERMINISTIC_ENCRYPTION_TYPE = "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic";
String RANDOM_ENCRYPTION_TYPE = "AEAD_AES_256_CBC_HMAC_SHA_512-Random";
```

Advantages:
- With Deterministic fields, we can apply search queries and also use them as indexed fields.
- And we can also continue to use Random encryption for the fields that we want.

**Comment by agoston** [comment]
That would undermine crypto strength by allowing rainbow table attacks. Of course that could be an accepted leverage between crypto and ease of index, but in the README I've outlined another solution for this:

https://github.com/bolcom/spring-data-mongodb-encrypt#encrypting-an-indexed-field

The upside of having a hash is that you could merge multiple fields into that hash, making it much harder to brute force the original values. Furthermore, if you carefully design your hash key space to be small enough, there will be multiple hits for each hash key, making if effectively impossible to determine the exact original values.

That aside, if you wish to make an MR that makes this pluggable (like the `CachedEncryptionEventListener` vs. `ReflectionEncryptionEventListener`), I'm happy to merge!

**Comment by serafimpinto** [comment]
Thanks for the reply. I understand your point and it is a balance between a crypto strength and the possibility to have deterministic encryption and random together.

In fact, to use the native mongo CSFLE features it needs the [libmongocrypt](https://github.com/mongodb/libmongocrypt) and [mongocryptd](https://docs.mongodb.com/manual/reference/security-client-side-encryption-appendix/#mongocryptd) _(Enterprise Edition Only)_ and on this project, you use your own manual encryption mechanism so to add this would be a totally different approach. 

I will take a look at this and if I came with a solution using this project I will propose a change. Until there I think you can close this. Thanks

**Comment by agoston** [comment]
The enterprise edition of mongo does a very similar thing indeed, but not compatible with this lib, nor is that the goal. The upside of this lib is that it's free, easily & seamlessly integrates with spring-data, and encryption happens strictly on client-side only.
