### ISSUE TITLE
Concurrency Issue with CachedEncryptionEventListener and Reflection Cache

### ISSUE THREAD

**Issue by AlexHetherington** [bolcom/spring-data-mongodb-encrypt#47]
If we launch an application using CachedEncryptionEventListener as our event listener, if we try to get many instances of the same class with encrypted data from the database simultaneously, sometimes we will get a failure like:

`org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.bson.types.Binary] to type [java.lang.String]`

I believe the issue is with ReflectionCache:34:

` reflectionCache.put(objectClass, nodes);`

Here mongodb-encrypt puts the object clazz in the reflection cache _before nodes are populated_.

If on a separate thread we try to get a different instance of the same class from the database _before the nodes cache is populated_ CachedEncryptionEventListener:37-38 will return an empty NODE and not do any decryption

```
Node node = node(event.getType());
if (node == Node.EMPTY) return;

```

I believe it will result in the above error

I don't have a confident suggestion for a fix - possibly you could only add the list of nodes to the reflection cache once it has been populated, but in the scenario I outlined above it would mean the list of nodes would be created twice.

**Comment by agoston** [comment]
Thank you for the probably most detailed bug report I ever received.

You are correct, I did not anticipate that we could have multiple threads running during initialization, while doing a massive refactor in version 2.5.

I will try to make a test coverage for the initialization part, to make sure we get the right results even under massive load at startup.

**Comment by agoston** [comment]
I added an integration test and managed to reliably reproduce this error.

So it turns out, `reflectionCache.put()` happens early because the method is recursive, and is relying on the node being available to avoid circular dependencies.

I am looking for a way to reliably fix this issue now.

**Comment by AlexHetherington** [comment]
Makes sense. Many thanks!

**Comment by agoston** [comment]
I've release 2.6.2 that fixes this issue.
