### ISSUE TITLE
not support for upsert

### ISSUE THREAD

**Issue by sdm5945** [bolcom/spring-data-mongodb-encrypt#51]
not support when I use org.springframework.data.mongodb.core.MongoTemplate#upsert(org.springframework.data.mongodb.core.query.Query, org.springframework.data.mongodb.core.query.Update, java.lang.Class<?>)，because this method don't call  maybeEmitEvent(event).

only support MongoTemplate????

**Comment by agoston** [comment]
`upsert` does not work with `Document`s, as such, it bypasses this library.

While it is possible to add support for this by parsing the `Update`, there are other APIs which do not use `Document` but a data model specific to the operation.

This is documented under https://github.com/bolcom/spring-data-mongodb-encrypt#caveats .

**Comment by sdm5945** [comment]
> 

upsert has worked with Document，I use upsert with @Indexed is effective。

**Comment by sdm5945** [comment]
> `upsert` does not work with `Document`s, as such, it bypasses this library.
> 
> While it is possible to add support for this by parsing the `Update`, there are other APIs which do not use `Document` but a data model specific to the operation.
> 
> This is documented under https://github.com/bolcom/spring-data-mongodb-encrypt#caveats .

thank you
