### ISSUE TITLE
Queries on encrypted fields

### ISSUE THREAD

**Issue by JolanenL** [bolcom/spring-data-mongodb-encrypt#52]
Hi, I have some trouble understanding the concepts after reading the description and earlier issues, please bear with me.

Let's say I do a find query on an encrypted field, will the library encrypt my query value so that there is a chance to match the encrypted fields?
And if encryption output is random as salted encryption would be, does that mean that there is no way to match the field directly without creating extra hash field and matching hashes instead?

Thanks!

**Comment by agoston** [comment]
No - this library only hooks into spring data's `afterLoad` and `beforeSave` events to encrypt/decrypt on the fly.
Please read the documentation about how to query/index encrypted fields.
